language: objective-c
osx_image: xcode9
xcode_sdk: iphonesimulator10.3
install:
- gem install xcpretty
script:
  - set -o pipefail
  - travis_retry xcodebuild -project KRAlertController.xcodeproj -scheme KRAlertController -destination "platform=iOS Simulator,name=iPhone 7" build-for-testing test | xcpretty
notifications:
  email: false
